# Generated by Django 5.0.4 on 2024-05-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_actor_birthday_actor_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(choices=[('USA', 'Estados Unidos'), ('BRAZIL', 'Brasil')], max_length=100),
        ),
    ]
